# Generated by Django 5.1 on 2024-08-27 10:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان نگاره')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Footer', verbose_name='نگاره')),
            ],
            options={
                'verbose_name': 'نگاره',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان اطلاعات')),
                ('content', tinymce.models.HTMLField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
    ]
