# Generated by Django 5.1 on 2024-08-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جوائز',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره 2')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': 'تاریخچه',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تنظیم عنوان',
                'verbose_name_plural': 'تنظیم عنوان',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'همکاران',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.CreateModel(
            name='AwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره')),
                ('title', models.CharField(max_length=255, verbose_name='لیبل')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardItem', to='AboutApp.award')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='عنوان')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='مقدار')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='AboutApp.about')),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده ها',
            },
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('year', models.CharField(max_length=5, verbose_name='سال')),
                ('text', models.TextField(verbose_name='متن ')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyItems', to='AboutApp.award')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='PartnerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.CharField(max_length=255, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerItems', to='AboutApp.partner')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
    ]
