# Generated by Django 5.1 on 2024-08-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='award',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historyItems', to='AboutApp.history'),
            preserve_default=False,
        ),
    ]
