# Generated by Django 5.1 on 2024-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0002_remove_historyitem_award_historyitem_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره'),
        ),
    ]
