# Generated by Django 5.1 on 2024-08-26 17:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سکشن')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان سکشن')),
                ('title1', models.CharField(max_length=100, verbose_name='عنوان متن اول')),
                ('text1', tinymce.models.HTMLField(verbose_name='توضیح متن اول')),
                ('title2', models.CharField(max_length=100, verbose_name='عنوان متن دوم')),
                ('text2', tinymce.models.HTMLField(verbose_name='توضیح متن دوم')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Service', verbose_name='آیکون')),
                ('video', models.FileField(blank=True, null=True, upload_to='Service', verbose_name='ویدئو')),
            ],
            options={
                'verbose_name': 'هدر',
                'verbose_name_plural': 'هدر',
            },
        ),
    ]
