# Generated by Django 5.1 on 2024-08-26 11:26

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Service', verbose_name='نگاره')),
                ('content', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('title2', models.CharField(max_length=100, verbose_name='عنوان دوم')),
                ('content2', tinymce.models.HTMLField(verbose_name='توضیحات دوم')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تنظیم عنوان',
                'verbose_name_plural': 'تنظیم عنوان',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('text', tinymce.models.HTMLField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'توضیح سرویس',
                'verbose_name_plural': 'توضیح سرویس',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='سوال')),
                ('text', tinymce.models.HTMLField(verbose_name='جواب')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqItems', to='ServiceApp.faq')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'پرسشها و پاسخ ها',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='لیبل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='ServiceApp.items')),
            ],
            options={
                'verbose_name': 'لیست',
                'verbose_name_plural': 'لیست ها',
            },
        ),
    ]
