# Generated by Django 5.1 on 2024-08-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='faq',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='ServiceApp.items'),
            preserve_default=False,
        ),
    ]
