# Generated by Django 5.1 on 2024-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_remove_faq_subtitle_faq_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='title_faq',
        ),
    ]
