# Generated by Django 5.1 on 2024-08-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0004_service_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
