# Generated by Django 5.1 on 2024-08-26 08:44

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'نام دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('category_slug', models.CharField(max_length=255, verbose_name='اسلاک دسته بندی')),
                ('date', models.CharField(max_length=50, verbose_name='تاریخ اجرای پروژه')),
                ('description', tinymce.models.HTMLField(verbose_name='متن')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ProjectApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Project', verbose_name='تصویر')),
                ('alt', models.CharField(max_length=255, verbose_name='عنوان تصویر')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'نگاره',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', tinymce.models.HTMLField(verbose_name='متن')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addtional', to='ProjectApp.project')),
            ],
            options={
                'verbose_name': 'توضیحات یشتر',
                'verbose_name_plural': 'توضیحات بیشتر',
            },
        ),
    ]
