# Generated by Django 5.1 on 2024-08-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'پرسش و پاسخ',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('tel', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('Address', models.TextField(verbose_name='نشانی')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='سوال')),
                ('text', models.TextField(verbose_name='جواب')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='ContactApp.faq')),
            ],
            options={
                'verbose_name': 'سوالات متدوال',
                'verbose_name_plural': 'سوالات متدوال',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام شبکه اجتماعی')),
                ('link', models.CharField(max_length=255, verbose_name='لینک شبکه اجتماعی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Contact', verbose_name='آیکون شبکه اجتماعی')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='ContactApp.info')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
