# Generated by Django 5.1 on 2024-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تنظیم عنوان',
                'verbose_name_plural': 'تنظیم عنوان',
            },
        ),
    ]
